# Site settings
title: Jiadao's Website
description: My persoanl webpage
url: "http://jiadaoz22.github.io/jiadao.github.io/"
baseurl: "/"

# Build settings
markdown: kramdown
# permalink: pretty

include:
  - assets

exclude: 
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore

# Jekyll settings
# sass:
#   style: compressed

# Collections
# collections:
#   gallery:
#     output: false
